Cargo.toml
src/common/grpc_client.rs
src/esp32/robot_client.rs
src/lib.rs
src/native/robot_client.rs

This a POC to support Grpc BiDi via Rust Streams

[RSDK-1793] Support bi di

---

.github/workflows/license_finder.yml
.github/workflows/test.yml
Makefile
etc/docker/Dockerfile
etc/docker/entrypoint.sh
examples/build.rs
examples/native/native.rs
src/common/motor.rs
src/native/robot_client.rs

Just laying out the bare minimum for CI to work. I have added the Dockerfile for the micro-rdk canon image which is used for the CI but can also be used as a dev environment. The image itself is around 10G we can probably reduce the size by being more selective about what we are pulling etc... 
For now the build step fails because we are relying on a existing robot to pull data from, we can either add an organisation secret that point to a robot on app.viam.com or find another approach, I am more tempted to find said other approach :)

[RSDK-2106] Add CI for micro-rdk

---

README.md

* edited w/ some of the feedback from [Viam for Microcontrollers](https://docs.google.com/document/d/1NgtcgX2NEwupTCKzfQTK4IBtVPePVLdg44G8NXT-jS4/edit)
* preparing for setup info to be added to docs

[DOCS-312] revise readme with feedback

---

examples/native/native.rs
src/common/encoder.rs
src/common/grpc.rs
src/common/registry.rs
src/common/robot.rs
src/gen/google.api.rs
src/gen/viam.app.data.v1.rs
src/gen/viam.app.mltraining.v1.rs
src/gen/viam.app.v1.rs
src/gen/viam.component.arm.v1.rs
src/gen/viam.component.camera.v1.rs
src/gen/viam.component.encoder.v1.rs
src/gen/viam.component.gantry.v1.rs
src/gen/viam.service.mlmodel.v1.rs
src/gen/viam.service.motion.v1.rs
src/gen/viam.service.slam.v1.rs
src/lib.rs

NOTE: I've sequestered all of the auto-generated changes from pulling in the encoder protobuf contract to the first commit for the reviewer's convenience

RSDK-2617 - add trait and gRPC API for encoder component

---

Cargo.toml
src/common/grpc.rs
src/common/webrtc/grpc.rs
src/common/webrtc/io.rs
src/common/webrtc/sctp.rs

Implement server side streaming with webrtc. Also contains some updates on sctp & grpc

[RSDK-3069 ] Server side webrtc streaming

---

src/common/base.rs
src/common/grpc.rs
src/common/motor.rs
src/common/stop.rs
src/esp32/base.rs
src/esp32/motor.rs
src/esp32/single_encoded_motor.rs
src/lib.rs

- Verified gpio motors work (`ABMotorEsp32` and `PwmDirMotorEsp32`)
- Make`Stoppable` a Super trait for `Base` and `Motor`

[RSDK-2619] gpio motor

---

src/common/base.rs
src/common/registry.rs
src/common/robot.rs
src/esp32/base.rs
src/esp32/single_encoder.rs

RSDK-2322 - add config support for single encoder and base

---

examples/esp32/esp32-server.rs
examples/native/native-server.rs
src/common/base.rs
src/common/board.rs
src/common/conn/server.rs
src/common/encoder.rs
src/common/entry.rs
src/common/motor.rs
src/common/movement_sensor.rs
src/common/registry.rs
src/common/robot.rs
src/common/sensor.rs
src/esp32/entry.rs
src/esp32/single_encoder.rs
src/lib.rs
src/native/entry.rs

expose internal model registry and component traits to users

[RSDK-3985] Modular Drivers

---

.github/workflows/publish.yml
.github/workflows/test.yml
Makefile
examples/build.rs
src/common/app_client.rs

Automatically publish a esp32-serrver binary when creating a tag. Treat rc release as pre-release

[RSDK-4960] Publish workflow

---

Cargo.toml
etc/docker/Dockerfile
examples/Cargo.toml

I have not run `cargo update` as part of this PR since it won't (yet) work until the repos are transferred.

RSDK-5397 Use forks from viamrobotics not npmenard

---

examples/Cargo.lock

as a follow-up to https://github.com/viamrobotics/micro-rdk/pull/103, I think?

update examples Cargo.lock

---

micro-rdk-installer/Cargo.lock
micro-rdk-installer/Cargo.toml
micro-rdk-installer/src/main.rs

Before:
10:26 $ ./micro-rdk-installer-macos write-flash --app-config ~/Downloads/viam-esp-main.json
```
<long silent pause>
✔ Please enter WiFi SSID · Viam-2G
✔ Please enter WiFi Password · ********
<silent pause>
<select port>
<silent pause>
[00:01:03] [========================================]    1806/1806    0x0
```
After:
```
10:43 $ ./target/debug/micro-rdk-installer  write-flash --app-config ~/Downloads/viam-esp-main.json
Downloading micro-RDK release from "https://github.com/viamrobotics/micro-rdk/releases/latest/download/micro-rdk-esp32-server.bin"
✔ Please enter WiFi SSID · Viam-2G
✔ Please enter WiFi Password · ********
Creating NVS partition with robot id: "7ee9575e-234f-4aac-8774-70a9111401c6", wifi ssid: "Viam-2G".
writing entry 1 of 14...
writing entry 2 of 14...
writing …
```

Added logs to installer

---

src/common/ina.rs
src/common/mod.rs
src/common/power_sensor.rs
src/common/registry.rs

Hardware tested with INA219, driver supports [INA219](https://www.ti.com/lit/ds/symlink/ina219.pdf) and [INA226](https://www.ti.com/lit/ds/symlink/ina226.pdf)

RSDK-5729 - implement INA power sensor

---

Cargo.toml
etc/docker/Dockerfile
examples/Cargo.lock
examples/Cargo.toml
examples/esp32-with-cred/esp32-server-with-cred.rs
examples/esp32/partitions.csv
src/common/grpc_client.rs
src/esp32/analog.rs
src/esp32/board.rs
src/esp32/encoder.rs
src/esp32/exec.rs
src/esp32/pulse_counter.rs
src/esp32/single_encoder.rs
src/native/exec.rs

bump-versions 

---

Cargo.toml
examples/Cargo.lock
examples/Cargo.toml
examples/build.rs
examples/esp32/esp32-server.rs
examples/esp32/partitions.csv
examples/native/native-server.rs
src/common/analog.rs
src/common/config.rs
src/common/digital_interrupt.rs
src/common/i2c.rs
src/common/motor.rs
src/common/registry.rs
src/common/robot.rs
src/esp32/entry.rs
src/esp32/i2c.rs
src/native/entry.rs

This covers RSDK-5875 and RSDK-2321, plus a small refactor of the config logic

Remove static config and Kind trait conversion

---

micro-rdk-installer/src/error.rs
micro-rdk-installer/src/main.rs

Not yet tested, opening PR somewhat prematurely

RSDK-5805 - support remembering serial port for espflash

---

.github/workflows/canary.yml
.github/workflows/canary_summary.yml

I forgot to copy over the python setup step from my testing branch before merging https://github.com/viamrobotics/micro-rdk/pull/138

set up python on runner for canary

---

Makefile
micro-rdk/src/common/analog.rs
micro-rdk/src/common/board.rs
micro-rdk/src/common/grpc.rs
micro-rdk/src/common/moisture_sensor.rs
micro-rdk/src/common/robot.rs
micro-rdk/src/esp32/analog.rs
micro-rdk/src/esp32/board.rs

PR untested, will test that analogs still work on physical hardware as code is being reviewed

RSDK-6860 - wrap AnalogReaders in Arc<Mutex> so Board implements Send

---

micro-rdk/src/esp32/certificate.rs

Allow generating a webrtc certificate at runtime

[RSDK-7254] generate webrtc cert on esp32

---

Cargo.lock
Cargo.toml
README.md
micro-rdk/Cargo.toml
micro-rdk/src/common/grpc.rs
micro-rdk/src/common/mod.rs
micro-rdk/src/common/provisioning/mod.rs
micro-rdk/src/common/provisioning/server.rs
micro-rdk/src/common/provisioning/storage.rs
micro-rdk/src/lib.rs

Add provisioning server and Storage trait

[RSDK-7248] add provisioning api

---

Makefile
micro-rdk/src/common/provisioning/server.rs
micro-rdk/src/common/provisioning/storage.rs
micro-rdk/src/esp32/mod.rs
micro-rdk/src/esp32/nvs_storage.rs

Add an NVS storage driver in preparation of supporting provisioning using the viam app

[RSDK-7496] add nvs driver

---

micro-rdk/src/common/app_client.rs
micro-rdk/src/common/grpc_client.rs
micro-rdk/src/esp32/entry.rs
micro-rdk/src/native/entry.rs

[RSDK-7387] Drop unneeded mut from app and gRPC clients

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
examples/esp32/esp32-server.rs
examples/native/native-server.rs
micro-rdk/src/common/app_client.rs
micro-rdk/src/common/provisioning/server.rs
micro-rdk/src/common/provisioning/storage.rs
micro-rdk/src/esp32/entry.rs
micro-rdk/src/native/conn/mdns.rs
micro-rdk/src/native/entry.rs

Adding mDNS service & examples. For now it uses MemroyCredential Storage so we can test the flow with the mobile app. We will do something more permanent for the esp32 at a later stage

[RSDK-7253] discovery mdns

---

micro-rdk-installer/src/main.rs

This fixes the issues with `write-flash` and `--monitor` mentioned [here](https://github.com/viamrobotics/micro-rdk/pull/204#issuecomment-2120965559).
command should now work as expected. 
Note: the previous app-image and new app-image must both be from the same variant of `examples`, ie `esp32-with-cred`.
Since we publish `esp32-with-cred`, if the old app image was build manually with `make build-esp32-bin`, the `monitor` will show an error such as 
```
I (16) esp32_server_with_cred::esp32: load vars from NVS...
I (32) esp32_server_with_cred::esp32: get namespace...
I (33) esp32_server_with_cred::esp32: loading creds...
I (34) esp_idf_svc::nvs: EspNvs dropped
I (38) esp_idf_svc::nvs: NvsDefault dropped
thread 'main' panicked at examples/esp32-with-cred/esp32-server-with-cred.rs:159:45: …
```

hotfix: `write-flash` command

---

micro-rdk/src/common/data_store.rs
micro-rdk/src/common/sensor.rs

Also includes a fix to data store tests

fix compile error when building without default features

---

micro-rdk/src/common/grpc_client.rs
micro-rdk/src/esp32/tls.rs

Add a keep alive timeout for both the HTTP2 layer and the Socket layer

[RSDK-7992] Add keepalive

---

micro-rdk/src/common/data_manager.rs

Justification available here: https://viam.atlassian.net/browse/RSDK-8036

RSDK-8036 - change data upload strategy to lose messages that fail to upload

---

micro-rdk/src/common/grpc.rs
micro-rdk/src/common/motor.rs
micro-rdk/src/gen/google.protobuf.rs
micro-rdk/src/gen/pb.rs
micro-rdk/src/gen/viam.app.mltraining.v1.rs
micro-rdk/src/gen/viam.app.packages.v1.rs
micro-rdk/src/gen/viam.app.v1.rs
micro-rdk/src/gen/viam.component.motor.v1.rs
micro-rdk/src/gen/viam.component.servo.v1.rs
micro-rdk/src/gen/viam.robot.v1.rs
micro-rdk/src/gen/viam.service.slam.v1.rs

NOTE: Hardware testing incomplete. Will not merge until then, but would appreciate a quick code review

RSDK-7751 - Implement new SetRPM for Motor API

---

micro-rdk/src/common/camera/fake_camera.rs
micro-rdk/src/common/grpc.rs
micro-rdk/src/common/webrtc/grpc.rs
micro-rdk/src/lib.rs

This PR adds the method needed to display an image on RC page in app.viam

[RSDK-7818] impl camera_render_frame

---

micro-rdk/src/common/grpc.rs

Update grpc.rs typo

---

micro-rdk/src/common/app_client.rs
micro-rdk/src/common/grpc.rs

exit() and esp_restart() both return nothing, so I assume they cannot fail and did not return an error

[RSDK-7692] Shutdown command

---

micro-rdk/src/common/config_monitor.rs

check to see if get_config is OK instead of unwrapping it

[RSDK-8202]fix bug

---

micro-rdk/src/common/app_client.rs
micro-rdk/src/common/config_monitor.rs
micro-rdk/src/common/conn/server.rs
micro-rdk/src/common/entry.rs
micro-rdk/src/native/entry.rs

addressing the request from [this PR](https://github.com/viamrobotics/micro-rdk/pull/251/files#r1664613484)

[RSDK-8121] - separate RPC host handling from robot credentials

---

micro-rdk/src/common/conn/server.rs

Three effects/changes here:
- No upgradable read lock is taken in periodic app client task executions, since this conflicts with the upgradable read lock in signaling. A plain read lock is used instead.
- No lock is held now across the periodic task invocation, so long running tasks (e.g. data sync across a low bandwidth channel) do not block each other / signaling.
- Errors observed by periodic app client task invocations no longer drop the app client, reverting on-error behavior to what existed prior to #275.
This is intended as a stopgap solution until we have a better design in mind.

[RSDK-8578] Revise locking for periodic app client tasks

---

templates/project/cargo-generate.toml
templates/project/viam.json

named it machine cloud credentials to reflect what's in app.viam's UI

[RSDK-8623] create viam.json using template prompt

---

micro-rdk/src/common/provisioning/server.rs
micro-rdk/src/esp32/provisioning/wifi_provisioning.rs

remove the associated type in wifimanager trait so that merging entrypoints will be easier.

[RSDK-8787] remove assoc type in wifi manager trait

---

DEVELOPMENT.md
README.md

@gvaradarajan - I missed updating the link while renaming a file in the prior review, and then noticed a copy-paste error in the title of the new page.

RSDK-8754 Fixup bad link and page title

---

micro-rdk-ffi/example/example.c
micro-rdk-ffi/include/micrordk.h
micro-rdk-ffi/src/ffi/config.rs
micro-rdk-ffi/src/ffi/runtime.rs

Includes support for building the FFI with pre-populated robot credentials

[RSDK-8807] support reading array of ints from config in C FFI

---

micro-rdk/src/common/conn/server.rs
micro-rdk/src/common/conn/viam.rs
micro-rdk/src/common/webrtc/api.rs

This slightly change the connection flow allowing both webrtc & http2 connection to move forward concurrently. This will also give us the option to increase the number of concurrent answerer. Note that there can only be one answerer listening on the /Answer endpoint at any time.

allow h2 and webrtc to move forward concurrently

---

micro-rdk/src/common/config_monitor.rs
micro-rdk/src/common/conn/viam.rs
micro-rdk/src/common/webrtc/api.rs

Remove semaphore and add a second remote answerer

remove semaphore from signaling task

---

micro-rdk/src/common/conn/viam.rs
micro-rdk/src/common/grpc.rs
micro-rdk/src/common/webrtc/api.rs
micro-rdk/src/common/webrtc/signaling_server.rs

These are follow-up items and TODOs from #347

[RSDK-8489] Cleanups and TODO items from review

---

micro-rdk/src/common/ota.rs

I moved away from `EspError` and `#[error(transparent)]` and have it return a string since there isn't a single place EspError happens (i.e. getting the app image header, getting the write handle, writing, aborting, etc). The essence of the message should still be captured in the string conversion

[RSDK-9214] add more expressive error types and messages

---

DEVELOPMENT.md

Viewable here: https://github.com/acmorrow/micro-rdk/blob/RSDK-9134/DEVELOPMENT.md#use-crate_cc_no_defaults

[RSDK-9134] Document macOS challenges with Homebrew python and ESP-IDF

---

Makefile

During testing, this pre-build step led to issues with some developer environments/workflows.

rm build ota dep for serve-ota

---

.canon.yaml
.github/workflows/esp32.yml
.github/workflows/license_finder.yml
.github/workflows/publish.yml
etc/docker/Dockerfile
etc/docker/docker.make
templates/project/.canon.yaml
templates/project/.github/workflows/publish.yml

This is split in two commits: the first makes the changes to the canon image and the versioning scheme it uses. If/when this PR is approved, I will rebuild the images from that commit and publish them.
The second commit adopts the new image and makes adjustments per the changes to the images.

[RSDK-10228] New canon image and changes to take advantage of it

---

micro-rdk-ffi/src/ffi/runtime.rs
micro-rdk-server/esp32/main.rs
micro-rdk/src/common/conn/viam.rs
templates/project/src/main.rs

Some symbols are not defined anymore in ESP-IDF5

[RSDK-8998] remove symbols

---

Cargo.lock
Cargo.toml
micro-rdk/src/esp32/conn/network.rs
templates/project/Cargo.toml.liquid

upgrade embedded-svc & esp-idf-svc so types are compatible.
Since esp-idf-svc exposes the scan sort methods I went ahead and removed our custom code

[RSDK-10193] upgrade crates

---

micro-rdk/src/common/data_store.rs
micro-rdk/src/common/ota.rs
micro-rdk/src/common/provisioning/server.rs
micro-rdk/src/common/webrtc/udp_mux.rs
micro-rdk/src/native/certificate.rs

to address all the clippy warnings to get CI green

native clippy fixes

---

canary/canary_ota.py

Will be followed up by a PR to deactivate the canary update on the release/0.4 branch

[RSDK-10404] fix canary OTA update

---

micro-rdk/src/common/grpc.rs
micro-rdk/src/common/mod.rs
micro-rdk/src/common/registry.rs
micro-rdk/src/common/robot.rs
micro-rdk/src/common/switch.rs
micro-rdk/src/lib.rs

I implemented the `FakeSwitch` based on the RDK implementation of it, [here](https://github.com/viamrobotics/rdk/blob/main/components/switch/fake/switch.go).
It's a zero-index counter. appears to work with the UI in app

[RSDK-10470] add switch component

---

micro-rdk/src/common/analog.rs
micro-rdk/src/common/camera/fake_camera.rs
micro-rdk/src/common/camera/mod.rs
micro-rdk/src/common/config.rs
micro-rdk/src/common/motor.rs
micro-rdk/src/common/registry.rs
micro-rdk/src/common/robot.rs

This covers components only. I am debating on updating services too

[RSDK-7822] Use API & Model triplet

---

Cargo.lock
Cargo.toml
micro-rdk-nmea-macros/src/attributes.rs
micro-rdk-nmea-macros/src/composition.rs
micro-rdk-nmea-macros/src/lib.rs
micro-rdk-nmea-macros/src/utils.rs
micro-rdk-nmea/Cargo.toml
micro-rdk-nmea/build.rs
micro-rdk-nmea/src/gen/mod.rs
micro-rdk-nmea/src/lib.rs
micro-rdk-nmea/src/messages/message.rs
micro-rdk-nmea/src/messages/pgns.rs
micro-rdk-nmea/src/parse_helpers/errors.rs
micro-rdk-nmea/src/parse_helpers/parsers.rs
micro-rdk-nmea/src/viamboat/sensors.rs

Only supports a specifically whitelisted set of PGNs, reasons are explained in code via comment.

[CONSULT-1024] generate structs for NMEA message formats from JSON
