- Cargo.toml
- examples/Cargo.toml
- examples/build.rs
- examples/esp32/esp32_static.rs
- examples/native/native.rs
- src/common/base.rs
- src/common/board.rs
- src/common/camera.rs
- src/common/config.rs
- src/common/motor.rs
- src/common/registry.rs
- src/common/robot.rs
- src/common/sensor.rs
- src/lib.rs
This PR sets the basic framework to process config during build time and have the ability to use it when running micro-rdk as to avoid hardcoding it.
During the build step we generate a rust representation of the config that can be used without much more processing by micro-rdk at runtime. Similarly to go a component's config gets consumed by the matching model constructor (see registry) the constructor can use helper functions to convert attributes to usable values. It can also extend the conversion support by implementing the TryFrom trait. 
For now only two fake models (board, motor) are supported, with planned support for sensors and analog reader before the close of the PR. Anything relevant to ESP32 will be in a separate PR given the need to refactor many of the current interfaces …
> [RSDK-1722] ConsumeStatic config

- src/common/adxl345.rs
- src/common/encoder.rs
- src/esp32/encoder.rs
- src/esp32/motor.rs
- src/esp32/pulse_counter.rs
- src/esp32/single_encoded_motor.rs
- src/esp32/single_encoder.rs
- src/lib.rs
Hardware Tests Conducted:
- two motor-encoder pairs on viam-rover working (single encoders)
- motor testing rig with quadrature encoder
> RSDK-2937 - implement single pin encoder for Esp32

- examples/esp32/esp32.rs
- src/esp32/board.rs
Behavior before:
- changed pin config to Input after reading the pin level, breaking ability to change pin state anytime afterwards
Behavior after:
- will not change pin configuration
- when pin level is set and floating, will read the level last set (given minimal environmental interference)
- when pin level is set and connected, will read the level of what is connected (low on ground, high on 3.3v)
> [RSDK-3397] stop pin config change when getting pin level

- src/common/analog.rs
- src/common/config.rs
- src/common/i2c.rs
- src/common/motor.rs
- src/esp32/i2c.rs
This was a change that I forgot to make in the [previous commit](https://github.com/viamrobotics/micro-rdk/commit/fbc7fc8f6bb2c7ef01f631fcef1987f612b61dcf). Without this, certain components that implemented from_config still could not be generated from dynamically acquired configs.
> RSDK-3169 - fix lack of support for non-static config structs in component generators

- src/common/adxl345.rs
- src/common/board.rs
- src/common/camera.rs
- src/common/encoder.rs
- src/common/motor.rs
- src/common/movement_sensor.rs
- src/common/mpu6050.rs
- src/common/registry.rs
- src/common/robot.rs
- src/common/sensor.rs
- src/esp32/encoder.rs
- src/esp32/motor.rs
This supports _implicit_ dependencies only; it does not make use of the 'depends_on' field (although this could be implemented in a later PR). I made this choice because it seems that we were headed in the direction of implicit rather than explicit dependencies in RDK anyway. The board is still always passed as a dependency to every component constructor.
Follow-up PRs (still under RSDK-2322) will implement dependency functions for the rest of the components for which such a thing is relevant.
> RSDK-2322 - implement support for component dependencies in config

- src/common/config.rs
- src/common/motor.rs
- src/common/robot.rs
This commit results in the following UX changes:
- prefixing the model name with "micro-rdk:builtin:" is no longer required when configuring a component
- the config cards for `gpio` motor, as well as for `accel-adxl345` and `gyro-mpu6050`, in the app UI can also now be used
> RSDK-3171 - remove special prefix requirement and fix string parsing bug

- .github/workflows/test.yml
- Makefile
- etc/docker/Dockerfile
- micro-rdk-installer/Cargo.lock
- micro-rdk-installer/Cargo.toml
- micro-rdk-installer/src/error.rs
- micro-rdk-installer/src/main.rs
This PR looks larger than it is. Unfortunately, for builds to work I have to commit the Cargo.lock file which creates a very large diff because of espflash's dependencies
Testing instructions
1. Download the viam.json config file from app
2. From the top level of the directory (not from within examples), run `MICRO_RDK_USE_NVS=true make build-esp32-with-cred-bin`
3. `cd micro-rdk-installer && cargo run -- write-flash --app-config=<path to viam.json file> --binary-path=<path to local copy of micro-rdk repo>/examples/target/esp32-server-with-cred.bin --monitor` 
4. Follow the instructions in the terminal (it should ask you to input your wi-fi SSID and then your wi-fi password)
> RSDK-4695 - installer CLI part 3: implement write and flash

- Cargo.toml
- examples/Cargo.lock
- src/common/board.rs
- src/common/digital_interrupt.rs
- src/common/grpc.rs
- src/esp32/board.rs
- src/lib.rs
Also contains a small refactor on board that goes part of the way to improving management of pin resources on the ESP32 across components (see `GPIOPin` struct)
Hardware Test Cases Conducted
- getting/setting level for a pin not configured as an interrupt
- getting level for a pin configured as an interrupt
- calling `GetDigitalInterruptValue` on the board from a Python SDK for a pin configured as an interrupt (touched the pin to a 3v3 connection repeatedly to increase the event count)
I'm willing to remove the pins subscription support for other drivers if we don't like that I used channels. I felt it might be ok because our cargo dependencies implied that we were already implicitly using them
> RSDK-4499 - add digital interrupt support to board

- micro-rdk-installer/Cargo.lock
- micro-rdk-installer/Cargo.toml
- micro-rdk-installer/src/error.rs
- micro-rdk-installer/src/main.rs
- micro-rdk-installer/src/nvs/request.rs
Test instructions:
1. Download a copy of the server config (viam.json) of a robot (from step 1 of the Setup tab)
2. `cd micro-rdk-installer && cargo run -- write-flash --app-config=<path to viam.json>  --monitor`
> RSDK-4249 - have installer download compiled binary of latest release when binary path not supplied

- src/common/board.rs
- src/common/grpc.rs
- src/esp32/board.rs
- src/esp32/pin.rs
- src/esp32/pwm.rs
- src/lib.rs
Tested on hardware: setting and getting PWM duty cycle and frequency works
This commit does not include having the motors in esp32/motor use pins via the board (if it does, potentially move the motor implementations to common?)
> RSDK-4784 - add pwm support to board

- src/common/gpio_motor.rs
Requiring "max_rpm" is unreasonable when we don't even support GoFor on motors by API call.
> don't require max_rpm in gpio motor config

- src/common/gpio_servo.rs
- src/common/grpc.rs
- src/common/registry.rs
- src/common/robot.rs
- src/common/servo.rs
- src/lib.rs
included in this PR
- new `Servo` trait with registration functions and corresponding gRPC handlers for Viam Servo API
- implementation of a configurable generic servo using a PWM signal on a GPIO pin `GpioServo` (model name is "gpio")
> RSDK-5599 - implement servo component

- src/common/generic.rs
- src/common/grpc.rs
- src/common/registry.rs
- src/common/robot.rs
- src/lib.rs
Part 1 of 2 for [RSDK-5725](https://viam.atlassian.net/browse/RSDK-5725). This implements the actual generic component API with the `GenericComponentTrait`. A follow-up PR will introduce that trait to all of the existing component types (along with the requisite gRPC handlers)
[RSDK-5725]: https://viam.atlassian.net/browse/RSDK-5725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-5725 - implement generic component API

- Makefile
- src/common/board.rs
- src/common/mod.rs
- src/esp32/board.rs
- src/esp32/mod.rs
- src/lib.rs
- src/native/mod.rs
Changes to crate documentation for developer use. 
Method descriptions try to mirror the [Python SDK](https://python.viam.dev/autoapi/viam/components/index.html).
This PR highlights different options for how documentation can be added and rendered, as well as the directory structure changes (individual `mod.rs` or using the root `lib.rs`).
If this is approved, I'll add docs for the other components.
use `make doc-open` to generate docs and view in browser
> `Board` docs

- src/common/mod.rs
- src/common/registry.rs
- src/common/wheeled_base.rs
- src/esp32/mod.rs
moved our wheeled_base into common and changed the model name to "micro_rdk_wheeled_base"
Will comment here when tested on hardware, but I didn't really change anything.
> RSDK-5740 - change esp32_wheeled_base to two_wheeled_base

- micro-rdk-installer/Cargo.lock
- micro-rdk-installer/Cargo.toml
- micro-rdk-installer/src/main.rs
corresponding commit on fork of espflash here: https://github.com/viamrobotics/espflash/commit/8f8e58b8b1f5509d2c406a98e6e92a6a72f10140
> RSDK-5787 - implement installer option to print monitor logs to file

- Cargo.toml
- Makefile
- examples/Cargo.lock
- src/common/grpc.rs
- src/esp32/pin.rs
- src/esp32/pwm.rs
There were a couple of issues with the first iteration of the PWM code. Firstly the order of argument of ` ledc_bind_channel_timer` was incorrect (thanks C...)  The other issue came from the way the underlying Ledc driver select the clock source when  timer is created. It will most likely select a slow clock when PWM frequency < 1000 are set which prevent a user from switching to a higher frequency. Now we are rebuilding the timer when changing frequency
> Updating PWM logic

- .github/workflows/canary.yml
- .github/workflows/canary_summary.yml
- canary/canary_test.py
- canary/daily_summary.py
- canary/requirements.txt
Testing the github actions on my own a little later before merging, but wanted to get input on the connectivity data published and the acceptability threshold in the meantime
Used the Viam Python SDK since the golang one has its own netcode that does not make use of rust-utils.
Currently implemented to get the following information every hour and save to our MongoDB instance as a database called "esp32_canary" under a collection called "hourly_results"
- could we connect to the robot?
- how long did it take to connect to the robot?
- how many attempts did it take to connect to the robot?
- could we get/set a GPIO pin on the ESP32?
- if there was a failure, we store the error as well
Additionally there is a daily summary compiled at 11:30PM UTC that records the following information and …
> RSDK-5973 - ESP32 connection canary

- etc/docker/Dockerfile
After this change, running `canon --profile ... env SCCACHE=1 ...` will enable `sccache` in the canon environment by setting `RUSTC_WRAPPER=/usr/bin/sccache` and `SCCACHE_DIR=/host/.sccache`, by analogy with the existing `.cargo-docker-registry` host-based cargo cache.
That makes it opt-in. It'd be nice, perhaps, if canon supported setting `env: ...` in your canon config file so you could opt-in to it persistently under a name, but it doesn't seem to. 
I'll confess to being very tempted to introduce as part of this change a new `.micro-rdk-canon-shared-state` or similarly named directory and push the `.cargo-docker-registry` and `.sccache` directories under it, without the leading `.`s. Let me know if you feel that's worthwhile, as it would be a pretty minimal change above what is here. …
> RSDK-6421 Add support for sccache to micro-rdk canon images

- src/esp32/i2c.rs
really should have caught this earlier
> fix incorrect key used for baudrate in i2c configuration

- Cargo.toml
- examples/Cargo.toml
- micro-rdk-installer/Cargo.toml
- micro-rdk-macros/Cargo.toml
- micro-rdk/Cargo.toml
This had been something I'd hoped to do as part of converting to a workspace per #149, but since I didn't finish the work for that PR it wasn't included. It's maybe controversial? I'm not sure.
Anyway, this change moves us to use workspace dependency inheritance for all dependencies in the workspace crates.
The only downside to doing this that I'm aware of is that `cargo add` doesn't currently have support for adding directly at the workspace level, so if we `cargo add` a new dependency, we will need to manually pull it up to the top-level `Cargo.toml`, at least until https://github.com/rust-lang/cargo/issues/10608 gets resolved one way or another.
On the other hand, with this change in place, if we do `cargo add` of an existing dependency in a new location, it will import it with …
> Workspace based dependencies

- .gitignore
- Cargo.toml
- Makefile
- components_esp32.lock
- examples/Cargo.toml
- micro-rdk/Cargo.toml
This changes things so that, by default, micro-RDK will be compiled as a library dependency in an external module or project (in other words, esp-idf-svc will not be compiled with the `binstart` feature in micro-RDK)
For all projects meant to be the main application on an esp32, the `binstart` feature will have to be specified for the micro-RDK dependency (see the changes in `examples/Cargo.toml` for an example)
This PR also exposes the `libstart` feature on esp-idf-svc
> add functionality to import micro-RDK as a library

- templates/project/.canon.yaml
Docs give instructions to use canon but without a canon.yaml it uses debian:latest and fails.
https://docs.viam.com/get-started/installation/prepare/microcontrollers/development-setup/
> Add canon.yaml to project template

- README.md
Wanted to submit a bug / help request this weekend but there was no link to JIRA on the README.
This is a copy-over from the RDK.
I'd **much rather** submit a github issue so enabling issues would also work.
> Add link to JIRA in README.md

- Makefile
- micro-rdk/Cargo.toml
- micro-rdk/buf.gen.yaml
- micro-rdk/src/common/data_collector.rs
- micro-rdk/src/common/math_utils.rs
- micro-rdk/src/common/mod.rs
- micro-rdk/src/common/robot.rs
- micro-rdk/src/common/sensor.rs
- micro-rdk/src/lib.rs
Part 1 of 2 PRs
The TODO comments are there to provide a sense of the direction of the architecture moving forward and will be removed before merge
For now, to run the tests introduced in the PR, add "data" to the default features in micro-rdk/Cargo.toml before calling `make test`
> RSDK-6992 RSDK-6993 - implement DataCollector pt. 1

- Cargo.lock
- Cargo.toml
- micro-rdk/Cargo.toml
- micro-rdk/src/common/data_collector.rs
- micro-rdk/src/common/data_store.rs
- micro-rdk/src/common/mod.rs
~~PR 1 of 2: This PR only implements the data store and its write functionality (reading returns an unimplemented error)~~. Added read functionality as well
For now, to run the tests introduced in the PR, add "data" to the default features in micro-rdk/Cargo.toml before calling make test.
> RSDK-7063 - implement data store

- micro-rdk/src/common/data_collector.rs
- micro-rdk/src/common/data_manager.rs
- micro-rdk/src/common/mod.rs
- micro-rdk/src/common/robot.rs
Creates a `DataManager` for use in data management. This implements data collection logic as well as the loop for running collections and data synchronization, but does not yet implement the actual synchronization logic (or the actual task for running data management), so the structure is likely to change. Moving forward it should receive its `DataCollectors` from the robot, and its `sync_interval_ms` from an instance of `RobotConfig`.
> start implementation of DataManager

- Cargo.toml
- cargo-generate.toml
According to the [Cargo Generate Book](https://cargo-generate.github.io/cargo-generate/usage.html#templates-in-subfolders), 
subfolders can be specified with a root-level `cargo-generate.toml`. 
Currently, when running `make build-esp32-bin`, the following warning will appear
```sh
➜ make build-esp32-bin
$ cargo +esp espflash save-image --package examples --merge --chip esp32 target/xtensa-esp32-espidf/esp32-server.bin -T examples/esp32/partitions.csv -s 4mb  --bin esp32-server --target=xtensa-esp32-espidf  -Zbuild-std=std,panic_abort --release
warning: /home/mperez/viam/micro-rdk/Cargo.toml: unused manifest key: template
Compiling proc-macro2 v1.0.78
Compiling unicode-ident v1.0.12
...
```
This change quites that warning.
> chore: decouple template manifest from Cargo.toml

- .gitignore
- examples/esp32-with-cred/esp32-server-with-cred.rs
- examples/esp32/esp32-server.rs
- templates/project/src/main.rs
Previously, micro-rdk would just throw a panic with a line number when failing to start wifi (ssid/pass misconfiguration, etc).
This change gives slightly better error messages and includes the `EspError` value, ex. `failed to start wifi: EspError(263)`.
Adding these changes highlighted a couple code smells. The changes were repeated in three separate areas in almost the same way. Would be great if we could move the wifi setup code into the micrordk for users to pull and initialize with a couple lines instead of the boilerplate. It also enables us to provide better error messaging; the current error outputs are esp specific and need to be looked up [here](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/error-codes.html)
> [RSDK-7439] chore: better wifi errors

- Cargo.lock
- Cargo.toml
- Makefile
- etc/docker/Dockerfile
- templates/project/Makefile
this PR bumps the espflash requirements to v3.0.0 and modifies the make commands to be compatible. 
note: using `--baud` works for both espflash 2.0.0 and 3.0.0 as opposed to the short flags `-b` for 2.0.0 and `-B` for 3.0.0.
Sticking to long flags with espflash will hopefully minimize compatibility issues moving forward.
> [RSDK-7386] bump espflash tooling to v3.0.0

- examples/native/native-server.rs
- micro-rdk/src/common/conn/server.rs
Per discussions, `ViamServer::serve` is going to need to be decomposed into co-routines which can run concurrently.
The current implementation only does that for incoming WebRTC connections. Incoming HTTP2 connections simply took over service until complete. This PR changes handling for HTTP2 connections to work similarly to how WebRTC connections work.
HTTP2 connections are afforded the highest priority, since this seemed closest in spirit to the existing behavior, where established inbound HTTP2 connection would simply block new connection handling.
Creating this as draft for now while I do some more testing, but please feel free to provide any feedback you may have now.
> RSDK-7387 Handle incoming http2 connections in a coroutine

- examples/build.rs
- examples/esp32-with-cred/esp32-server-with-cred.rs
- examples/esp32/esp32-server.rs
- micro-rdk-installer/src/nvs/data.rs
- micro-rdk-installer/src/nvs/request.rs
- micro-rdk/src/esp32/tcp.rs
- micro-rdk/src/esp32/tls.rs
Essentially remove support for setting a CA cert in  the TLS config and use a TcpListener instead of a raw socket
> Fix esp32's HTTP2 server

- micro-rdk/src/common/data_manager.rs
- micro-rdk/src/common/data_store.rs
- micro-rdk/src/lib.rs
This refactor was necessary to enable the `DataManager` to preserve data when it fails to upload (upload logic still not included)
> refactor store to return a reader that only consumes on flush

- Cargo.lock
- Cargo.toml
- micro-rdk-installer/src/error.rs
- micro-rdk-installer/src/main.rs
Updates micro-rdk-installer to use latest espflash updates. 
[Our fork](https://github.com/viamrobotics/espflash/tree/monitor-output) makes some slight modifications to the underlying structs and adds additional logic to writing monitoring logs to an output file. 
The changes made to the installer mimics that of how `cargo-espflash` uses the `espflash` crate; we define our own wrapper `Command`s that hold the crate's flattened structs (ex `FlashArgs`, `MonitorArgs`).
This currently is just at the point of compiling. 
Still need to confirm the installer's before and after behavior (especially for commands in current docs)
**Breaking Changes**
- `WriteFlash.binary_path` -> `WriteFlashArgs.flash_args.bootloader`
- `WriteFlash.baud_rate` -> `WriteFlashArgs.monitor_args.baud`
- …
> [RSDK-7386] bump espflash deps to v3.0.0

- Cargo.lock
- Cargo.toml
- micro-rdk/src/native/tls.rs
This PR updates rustls and viam-rust-utils allowing to relax the pinned version of futures-rustls
> [RSDK-7221] relax pinned versions of rustls

- micro-rdk/src/common/app_client.rs
- micro-rdk/src/common/conn/server.rs
- micro-rdk/src/common/grpc_client.rs
A small simplification: drops a lifetime out of three important structs, so it seems worthwhile for the small memory cost of holding the URI in an owned string.
> [RSDK-7387] Drop lifetime from GrpcClient, AppClient, and ViamServer

- examples/esp32-with-cred/esp32-server-with-cred.rs
- examples/esp32/esp32-server.rs
- examples/native/native-server.rs
- micro-rdk/src/common/app_client.rs
- micro-rdk/src/common/conn/network.rs
- micro-rdk/src/common/conn/server.rs
- micro-rdk/src/common/mod.rs
- micro-rdk/src/esp32/conn/network.rs
- micro-rdk/src/esp32/entry.rs
- micro-rdk/src/esp32/mod.rs
- micro-rdk/src/native/entry.rs
- templates/project/src/main.rs
Introduces the following behavioral changes:
- at the beginning of `main_esp32` in `esp32-server.rs` and `esp32-server-with-cred`, there is now a continuous loop for connecting to Wi-Fi rather than simply panicking when unsuccessful
- in `ViamServer::serve`, if the base station remains connected but there is not internet access, the loop now continues without attempting to connect signaling
- in `ViamServer::serve`, if the base station is disconnected, the `app_client` is dropped until network connection has been re-established
- we now attempt reconnection upon receipt of a station disconnected event (while the station is disconnected, the event is repeatedly fired on what seems to be a safe interval)
**NOTE: The templates have not been adjusted because they point to the last released …
> stabilize server behavior on network interruptions

- Cargo.lock
- Cargo.toml
- micro-rdk-installer/Cargo.toml
- micro-rdk-installer/src/error.rs
- micro-rdk-installer/src/main.rs
- micro-rdk-installer/src/nvs/request.rs
tested with local app image on running device:
`cargo r -p micro-rdk-installer -- update-app-image --binary-path target/xtensa-esp32-espidf/esp32-server.bin`
The `update-app-image` command does the following in sequence:
- read the partition table of a currently running device
- download/read the new/selected image into memory
- compare the partition tables between the old app image and new one
- if they do not match, prompt user to re-build and flash device from scratch
- overwrite the running device's app image with the new one
Modifications are restricted to just the factory partition, leaving pre-existing NVS data intact.
> [RSDK-6253] Update a device's image while retaining credentials data

- micro-rdk/src/common/sensor.rs
- this change is in conjuction with updating the micro-rdk-esp32-sensor-examples pr 
- Support #from EspError for SensorError
> [RSDK-7801] Update sensorerr with esperr

- micro-rdk/src/common/data_store.rs
in `StaticMemoryDataStore::new` if no collector were configured then the `fetch_or` operation on `DATA_STORE_INITIALIZED` will still complete and incorrectly store true. Further call to `StaticMemoryDataStore::new` will always fail
> fix data store test

- micro-rdk/src/esp32/provisioning/wifi_provisioning.rs
Two changes :
1) SSID so it's more explicit
2)  Convert RSSI to signal strength as this is what Provisioning API expects
> Convert RSSI to signal strenght

- micro-rdk/src/common/app_client.rs
- micro-rdk/src/common/data_manager.rs
- micro-rdk/src/common/data_store.rs
This also addresses the bug of data collection pausing when the ESP32 is offline because the attempt to upload data hangs, never releasing the lock on the store.
> chunk upload requests in data management

- Cargo.lock
This is partially to pull in any potential bugfixes from our dependent packages and partially to register our new workspace member (micro-rdk-modular-driver-example) in Cargo.lock
> update dependencies in Cargo.lock

- micro-rdk/src/common/conn/server.rs
- micro-rdk/src/esp32/tls.rs
we've added a wrapper around the foreign `esp_tls_t` pointer and implemented Drop to ensure that it is always cleaned up in appropriate cases
> fix memory leak occurring when wifi is connected but app is unreachable

- micro-rdk/src/common/data_manager.rs
- micro-rdk/src/common/robot.rs
This fixes two issues : 
1) on any errors the collector task will not terminate and continue to attempt collecting
2) If any collector fails forever or transiently it will not  prevent collecting other records
> [RSDK-8131] Avoid killing the collector task on any error

- micro-rdk/src/esp32/provisioning/wifi_provisioning.rs
while going through provisioning with @EshaMaharishi, we couldn't find device mac address in monitor output; tries to print MAC in monitor before MAC is set with FUSE at L33 here. This just makes things clear. should we also log the default provisioning password while we're at it?
> log ssid to output

- micro-rdk/src/esp32/conn/network.rs
Change the connection behavior to do a full scan and selecting the AP with the strongest signal, instead of connecting to the first found AP which may not be the best AP.
> connect to best AP

- micro-rdk/src/common/grpc_client.rs
- micro-rdk/src/native/entry.rs
In some scenario the streamed RPC message can be split and the previous code would fail with a panic in this case. 
This PR fixes this behavior and introduce a test to replicate the issue
> [RSDK-8225] Fix panic in signaling path

- templates/project/Cargo.toml
Cargo doesn't allow for newlines when we split it out. I had tested the generation but somehow hadn't checked if compilation was broken.
> hotfix: template project toml invalid newlines

- Cargo.lock
- Cargo.toml
- examples/modular-drivers/src/wifi_rssi_sensor.rs
- micro-rdk-server/Cargo.toml
- micro-rdk-server/esp32/main.rs
This PR is just to migrate the `free_heap_sensor` from examples to the main micro-rdk builtins with minimal modifications. 
A follow-up ticket [RSDK-8353](https://viam.atlassian.net/browse/RSDK-8353) has been made to migrate builtin-sensors to a separate crate in the workspace.
Currently, it's not feature-gated from builtins due to its utility, but it may be worthwhile to eventually feature-gate this and similar tools under a `debug` flag or something. I can gate it in this PR behind the builtin-components flag if that's the concensus.
[RSDK-8353]: https://viam.atlassian.net/browse/RSDK-8353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [RSDK-8201] add heap sensor as builtin component

- micro-rdk-installer/src/main.rs
- micro-rdk-installer/src/nvs/request.rs
as `micro-rdk-installer write-flash` doesn't require a path or version to run, it will flash the device completely with the latest build immediately, overwriting stored configs.
During development, whether by poor naming of the options or me misremembering, I've had to quickly cancel so my configs don't get wiped. This prompt will give a user a chance to decline if this (or flashing with latest) is not the desired outcome.
For scripts where flashing latest is the desired behavior, `micro-rdk-installer write-flash --version latest` will work.
> Installer write flash prompt

- micro-rdk/src/common/app_client.rs
- micro-rdk/src/common/conn/server.rs
There is currently an instability on ESP32s that we believe is being caused by a request to the Viam App properly resolving but hanging on dropping the TLS context. This causes signaling to hang and blocks all incoming requests rendering the machine inaccessible and unable to move forward with any of its other tasks. The purpose of this PR is two-fold: we want to collect more data around the frequency with which these tasks hang and when all the tasks are in such a state we want to prompt a restart that will start of all the tasks anew. 
This is intended to be temporary until the investigation resolves and a proper fix is scoped out.
> STOPGAP MEASURE - panic when too many PeriodicAppClientTasks are hanging

- Cargo.lock
- Cargo.toml
- micro-rdk-ffi/src/ffi/runtime.rs
- micro-rdk-server/esp32/main.rs
- micro-rdk-server/native/main.rs
- micro-rdk/Cargo.toml
- micro-rdk/src/common/entry.rs
- micro-rdk/src/common/log.rs
- micro-rdk/src/esp32/log.rs
- micro-rdk/src/esp32/mod.rs
- micro-rdk/src/lib.rs
- micro-rdk/src/native/log.rs
- micro-rdk/src/native/mod.rs
This commit allows for upload of logs to app.viam.com. All logs will be uploaded EXCEPT the following:
1. System logs on the ESP32 that are performed using [ESP_LOG_EARLYx](https://docs.espressif.com/projects/esp-idf/en/v4.4/esp32/api-reference/system/log.html#how-to-use-this-library), such as those coming from "boot", "esp_image", "cpu_start", etc
2. Any logs performed on panic
Additionally, this feature will break upon upgrade to version 1.49 of esp-idf-svc because their `EspLogger` has changed from an empty public struct to one with a private constructor, leaving it unable to be wrapped by `ViamLogger`. I've opened an issue with esp-rs [here](https://github.com/esp-rs/esp-idf-svc/issues/476)
> [RSDK-8612] capture and cache logs, then upload to app.viam.com

- micro-rdk/src/common/data_manager.rs
- micro-rdk/src/common/robot.rs
Fixes an issue where, when the user disables the "Capturing" and/or "Syncing" flag in the data management service config, the corresponding functionality is not turned off
> [RSDK-8673] respect sync_disabled/capture_disabled flags in data config

- micro-rdk/src/common/data_collector.rs
- micro-rdk/src/common/robot.rs
In app, you can "turn off" individual data capture methods, but the micro-RDK infrastructure does not respect this setting. This fixes that.
> [RSDK-8757] allow disabling of individual capture configs

- Cargo.lock
- Cargo.toml
- etc/docker/Dockerfile
- micro-rdk-ffi/include/micrordk.h
- micro-rdk-server/Cargo.toml
- micro-rdk/Cargo.toml
- micro-rdk/src/esp32/conn/mdns.rs
- micro-rdk/src/native/tcp.rs
- templates/module/Cargo.toml
- templates/project/Cargo.toml
There are many crates with newer versions that are source compatible with the micro-rdk. Apply those upgrades, pin those that cannot be upgraded, and ticket identified future work.
- Apply manual pins
- cargo upgrade --rust-version 1.76 --recursive -i
- cargo update
- Upgrade mentions of rust 1.75 to rust 1.76
- Add TODOS with tickets for pins and other future upgrades
> [RSDK-8999] Bulk upgrade crates

- micro-rdk-ffi/src/ffi/runtime.rs
- micro-rdk-server/esp32/main.rs
- micro-rdk-server/native/main.rs
- micro-rdk/src/common/conn/viam.rs
- micro-rdk/src/common/credentials_storage.rs
- micro-rdk/src/esp32/nvs_storage.rs
- templates/project/src/main.rs
[This PR](https://github.com/viamrobotics/micro-rdk/pull/338) introduced a bug where when upgrading systems to 0.3.1 the server will enter a boot loop because app address wouldn't have been stored before. This PR introduce a fix to default to app.viam.com and stores that if app address is not present in storage. In the future (like a month or two) this commit should be reversed so that the implementation in the PR remains the one we use.
> Fix boot loop when upgrading a device to 0.3.1

- DEVELOPMENT.md
- examples/modular-drivers/README.md
The previous line was not working for some reason when used in an actual project. This new way is more canonical to Cargo anyway I believe.
> adjust README module dependency example

- Makefile
- etc/docker/Dockerfile
- etc/docker/README.md
- micro-rdk-server/Cargo.toml
- micro-rdk-server/esp32/ota_8mb_partitions.csv
- micro-rdk-server/esp32/partitions.csv
- micro-rdk/Cargo.toml
- micro-rdk/src/common/conn/viam.rs
- micro-rdk/src/esp32/mod.rs
- micro-rdk/src/esp32/ota.rs
Next Steps after this PR:
- Convert OtaService to async `Task` [RSDK-9195](https://viam.atlassian.net/browse/RSDK-9195?atlOrigin=eyJpIjoiODAxZDBiM2Y2MzQ3NDIxMGFkMzFiZjY1OTEyYzg3OTciLCJwIjoiaiJ9)
- Use hyper::http2/http1 instead of `EspHttpClient` to reduce code size [RSDK-9198](https://viam.atlassian.net/browse/RSDK-9198?atlOrigin=eyJpIjoiOTgyMWYzNGVjOTc3NGUyZmE2ZWFhZTA4YzNjOTcxMGYiLCJwIjoiaiJ9)
- Add exponential backoff [RSDK-9196](https://viam.atlassian.net/browse/RSDK-9196?atlOrigin=eyJpIjoiYTIzNjFhOWIwOWUyNGI4NTk2NTJlNDI1ODg2NDY4OTYiLCJwIjoiaiJ9)
- Finalize ota init criteria (change in url/version in ServiceConfig, app_desc_t, etc) [RSDK-9197](https://viam.atlassian.net/browse/RSDK-9197?atlOrigin=eyJpIjoiMzM4YjE4NzM1NTI0NDBlZjk0OTUzMWQxYzNiMGY4MmYiLCJwIjoiaiJ9)
Changes in this PR for …
> [RSDK-8930] Add OTA

- Cargo.lock
- Cargo.toml
- micro-rdk/Cargo.toml
- micro-rdk/src/common/app_client.rs
- micro-rdk/src/common/conn/server.rs
- micro-rdk/src/common/conn/viam.rs
- micro-rdk/src/common/grpc.rs
- micro-rdk/src/common/mod.rs
- micro-rdk/src/common/webrtc/api.rs
- micro-rdk/src/common/webrtc/ice.rs
- micro-rdk/src/common/webrtc/signaling_server.rs
- micro-rdk/src/esp32/dtls.rs
I will add inline annotations to provide context on the current state of things, and what needs to happen next.
> [RSDK-8489] Implement local webrtc signaling

- micro-rdk/src/common/webrtc/api.rs
Inside `run_ice_until_connected` a detached task is spawned for `ICEAgent::run`. That task can be canceled by calling `done` on the associated `AtomicSync` (`WebRtcApi::ice_agent`). In normal operation, that happens when the `AtomicSync` is stashed into a created `WebRTCConnection` which does indeed call `done` on the `AtomicSync` in its `Drop` implementation.
However, if `WebRtcApi::connect` launches the `ICEAgent::run` task in `run_ice_until_connected`, but does not proceed far enough to create the `WebRTCConnection`, then the detached task will never stop.
This exact scenario can happen if a client issues two WebRTC connection requests, one via app.viam.com signaling and the other via local signaling, and one of them gets cancelled during the critical window. It could also happen if a …
> [RSDK-9213] Ensure ice agent is terminated if signaling doesn't complete

- micro-rdk/src/common/conn/viam.rs
- micro-rdk/src/common/credentials_storage.rs
- micro-rdk/src/common/ota.rs
- micro-rdk/src/esp32/nvs_storage.rs
Instead of storing the OTA ServiceConfig in storage like originally planned, using the cached robot config achieves the same effect.
Still testing on hardware, will update when verified
> [RSDK-9283] add ota metadata storage, compare stored and latest

- micro-rdk/src/common/ota.rs
This adds a retry in the event a connection cannot be established (ex no network connection).
It does not implement resumable download.
It compiles, but need to verify on native and hardware. won't merge before doing so
> [RSDK-9196] add init connection retry

- micro-rdk/src/common/webrtc/api.rs
- micro-rdk/src/common/webrtc/ice.rs
- micro-rdk/src/common/webrtc/udp_mux.rs
Failing to resolve the STUN server should not crash, since this is a realistic scenario during an offline reboot.
Similarly, failing to resolve or reach the STUN server shouldn't inhibit generating a local candidate based on the local host/port, since this can be used now by local signaling.
> [RSDK-9296] [RSDK-9310] Improve interactions with STUN server

- micro-rdk/src/common/ota.rs
The maximum firmware size was statically set for 4MB, however partition tables can vary in size.
I've left the max size when downloading natively at 4MB (for debug/dev purposes, can be bumped easily).
On an esp32, we get the partition info for the next ota partition to be written to and use that to determine the limit.
This is great since we can use the destination's size instead of inferring. 
Won't merge until after final changes are verified on hardware.
> [RSDK-9200] determine max firmware size dynamically

- micro-rdk/src/common/ota.rs
the dead code and wrong error variant somehow got through ci on earlier merge. this fixes it. added a couple small changes to logs too
> fix native errors for ota

- micro-rdk/src/common/config_monitor.rs
- micro-rdk/src/common/conn/viam.rs
- micro-rdk/src/common/ota.rs
This PR:
- moves ota logic to the config monitor
- ~uses a `while let Err()` loop on `ota.update()` to ensure retries, **blocking other config changes from being applied**~.
- uses the periodic nature of the `ConfigMonitor` (every 10sec by default) to retry failed OTA attemps
- ~addresses ticket [RSDK-9594](https://viam.atlassian.net/browse/RSDK-9594) in the config monitor, haven't checked if this change needs to be made in other parts of the codebase.~
[RSDK-9594]: https://viam.atlassian.net/browse/RSDK-9594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [RSDK-9593] move ota to config monitor, config monitor restart hook 

- micro-rdk/src/lib.rs
the `global_network_test_lock` is used to serialize access to network resources to ensure parallelized tests don't trip over one another. We don't actually care to propagate poisons across tests because each test is meant to be self-contained and the underlying network resources are in-fact available.
> [RSDK-9366] Clear poisoned lock in tests

- Cargo.lock
- Cargo.toml
- micro-rdk-ffi/micrordklib-idf-component/idf_component.yml
Compare with https://github.com/viamrobotics/micro-rdk/commit/bb050e53179cd419ca7f4de670142d1a566da4df
- We don't want to update `micro-rdk-ffi/micrordklib-idf-component/CMakeLists.txt` because that's pinned to 0.3.0 per https://viam.atlassian.net/browse/RSDK-9493 until 0.4.0 GA.
- We don't want to update any templates, they should remain pinned to 0.3.3 for now, until 0.4.0 GA.
> bump versions for 0.4.0-rc1

- Cargo.toml
- etc/docker/Dockerfile
- etc/ota-dev-server/Cargo.toml
- micro-rdk-ffi/Cargo.toml
- micro-rdk-server/Cargo.toml
- micro-rdk/Cargo.toml
- templates/module/Cargo.toml
- templates/project/Cargo.toml
Noticed some explicit dependencies in non-root Cargo.toml, so fixed that and hunted down some other small inconsistencies and stale TODOs. No urgency on this, not trying to make 0.4.0 with it, but I would like to get it landed after 0.4.0 as it'll go stale quickly.
> Cleanup some misc Cargo.toml funk across the project

- examples/esp-idf-component/main/main.c
- micro-rdk-ffi/include/micrordk.h
- micro-rdk-ffi/src/ffi/runtime.rs
- micro-rdk-server/esp32/main.rs
- micro-rdk-server/native/main.rs
- micro-rdk/src/common/conn/viam.rs
- micro-rdk/src/common/credentials_storage.rs
- micro-rdk/src/common/ota.rs
- micro-rdk/src/common/provisioning/server.rs
- micro-rdk/src/esp32/nvs_storage.rs
- templates/project/src/main.rs
Implements the storage traits for any type we can iterate over, we can then easily pass an array of a vec as a storage to viam server. 
With this something like
`let storage = vec![
NVSStorage::new("nvs").unwrap(),
NVSStorage::new("nvs2").unwrap(),
];`
Will allow use to store the robot data over multiple NVS 
I didn't want to add an extra type to represent a collection of storage and this way the logic is driven by the underlying storage implementation.
> Rsdk 9697 support multiple nvs

- templates/module/Cargo.toml
- templates/project/Cargo.toml
Last bit of 0.4.0. I have an idea for how to not need to do this for 0.4.1: https://viam.atlassian.net/browse/RSDK-9734
> [RSDK-9694] Bump template versions to 0.4.0

- Makefile
- examples/esp-idf-component/partitions.csv
- micro-rdk-server/esp32/ota_8mb_partitions.csv
- micro-rdk-server/esp32/partitions.csv
- templates/project/partitions.csv
Standardize on a new partition scheme using two OTA segments at 3968k each, 80k NVS, and 128k coredump.
> [RSDK-9647] Standardize on 8MB OTA capable partition scheme

- micro-rdk/src/common/conn/viam.rs
the test has occasionally tripped, poisoning the `global_network_lock` (fixed). 
It's unclear how much time it would be needed to ensure it doesn't trip (or if other manageable factors are involved), but 1sec seems like a still-acceptable upper-bound on a single test. still faster than running the whole CI workflow again.
If other tests with similar timeouts have this issue it might make sense to make the timeout value global for tests.
> [RSDK-9365] fix flaky test

- Cargo.lock
- Cargo.toml
- micro-rdk-nmea-macros/Cargo.toml
- micro-rdk-nmea-macros/src/attributes.rs
- micro-rdk-nmea-macros/src/composition.rs
- micro-rdk-nmea-macros/src/lib.rs
- micro-rdk-nmea-macros/src/utils.rs
- micro-rdk-nmea/Cargo.toml
- micro-rdk-nmea/src/lib.rs
- micro-rdk-nmea/src/messages/mod.rs
- micro-rdk-nmea/src/messages/pgns.rs
- micro-rdk-nmea/src/parse_helpers/errors.rs
- micro-rdk-nmea/src/parse_helpers/parsers.rs
This is the first PR actually introducing the procedural macro. As explained in the [previous commit](https://github.com/viamrobotics/micro-rdk/pull/377#issue-2776548392), it is recommended that one uses `cargo expand` in the micro-rdk-nmea directory to view the code that is generated by the macro used in the example PGN structs.
This PR includes
-  parsing logic for the message header
- logic for parsing a message struct used by the procedural macro itself
- procedural code generation for messages using number and lookup field types
The next PR will include
- procedural code generation support for array and fieldset fields (also understood as "repeated fields")
> [CONSULT-469] - introduction of NMEA message macro

- Cargo.lock
- Cargo.toml
- micro-rdk-ffi/micrordklib-idf-component/CMakeLists.txt
- micro-rdk-ffi/micrordklib-idf-component/idf_component.yml
- templates/module/Cargo.toml
- templates/project/Cargo.toml
This is the commit I would like to tag as 0.4.0-rc1.
Along with the usual update of version numbers, there are some other simplifications here: 
- It starts using the tag name rather than a git hash in the template configs. This will mean we won't need a post release commit to update the templates with the now-known SHA1 of the release commit.
- It moves both templates to use the same style of declaration for the micro-rdk dependency.
- The `micro-rdk-ffi/micrordklib-idf-component/CMakeLists.txt` infrastructure now *derives* the version information from the version metadata in `micro-rdk-ffi/micrordklib-idf-component/idf_component.yml` by way of the `COMPONENT_VERSION` ESP-IDF CMake variable. This eliminates a duplicative touchpoint for releases.
- The version number in …
> [RSDK-9734] Release 0.4.1-rc1 and reduce number of release touchpoints

- .github/workflows/publish.yml
- .github/workflows/upload_bucket.yml
to reference something within the repo (ex `./.workflows/...`), you need to check out the repo at some point within the step. Instead of adding an extra step, we can reference a github repo path which does not need checkout
> use abs path, not rel path

- Cargo.lock
- Cargo.toml
- micro-rdk-ffi/micrordklib-idf-component/CMakeLists.txt
- micro-rdk-ffi/micrordklib-idf-component/idf_component.yml
- templates/module/Cargo.toml
- templates/project/Cargo.toml
I had to remove the `COMPONENT_VERSION` - I didn't realize it was ESP-IDF 5 only, and I made a mistake in my testing which made it appear that it was working. I've filed https://viam.atlassian.net/browse/RSDK-9841 so we can come back to it once we are on ESP-IDF 5.
Otherwise, this is a boring update of the version from `-rc3` to `-rc4` and a run of `cargo update`.
> Release v0.4.1-rc4 to fix workflow and component version issues

- .github/workflows/publish.yml
- add `on: workflow_dispatch` to publish.yml, but suppress the actual publish step in this case
faster iterative testing of publish.yml workflow
> add workflow_dispatch to publish.yml

- .github/workflows/publish.yml
added a the full json credentials. according to the google auth actions doc, will not work for gsutil, so using gcloud instead.
> add gcp auth, use updated sdk action

- .github/workflows/publish.yml
linux `apt install` step was failing because it didn't call `apt update` first
> [RSDK-9875] fix linux build deps command

- .github/workflows/canary_ota.yml
- .github/workflows/publish.yml
appears to be working, executed from `publish.yml` job here: https://github.com/viamrobotics/micro-rdk/actions/runs/13076878920
> [RSDK-9817] add required secrets during publich.yml call to canary_ota.yml

- Makefile
- micro-rdk-nmea/src/lib.rs
- micro-rdk-nmea/src/messages/pgns.rs
- micro-rdk/src/common/conn/server.rs
- micro-rdk/src/common/robot.rs
- micro-rdk/src/common/sensor.rs
- Run all tests in the workspace and do not fail fast
- Avoid need to reiterate PGN numbers in the PGN enum macro.
> PGN testing

- Makefile
- micro-rdk/src/common/app_client.rs
- micro-rdk/src/common/config.rs
- micro-rdk/src/common/data_collector.rs
- micro-rdk/src/common/data_store.rs
- micro-rdk/src/common/robot.rs
- micro-rdk/src/common/sensor.rs
- micro-rdk/src/gen/api_version.rs
- micro-rdk/src/gen/google.api.rs
- micro-rdk/src/gen/google.protobuf.rs
- micro-rdk/src/gen/google.rpc.context.rs
- micro-rdk/src/gen/google.rpc.rs
- micro-rdk/src/gen/pb.rs
- micro-rdk/src/gen/proto.stream.v1.rs
- micro-rdk/src/gen/viam.app.agent.v1.rs
- micro-rdk/src/gen/viam.app.build.v1.rs
- micro-rdk/src/gen/viam.app.data.v1.rs
- micro-rdk/src/gen/viam.app.datasync.v1.rs
- micro-rdk/src/gen/viam.app.mlinference.v1.rs
- micro-rdk/src/gen/viam.app.mltraining.v1.rs
- micro-rdk/src/gen/viam.app.v1.rs
- micro-rdk/src/gen/viam.common.v1.rs
- micro-rdk/src/gen/viam.component.arm.v1.rs
- micro-rdk/src/gen/viam.component.button.v1.rs
- micro-rdk/src/gen/viam.component.camera.v1.rs
- micro-rdk/src/gen/viam.component.switch.v1.rs
- micro-rdk/src/gen/viam.robot.v1.rs
- micro-rdk/src/gen/viam.service.discovery.v1.rs
- micro-rdk/src/lib.rs
Viam AgentConfig apis were updated recently that adds new convenience wrappers (`[get/set/has]NetworkConfiguration`) for downstream work (multiple wifi support). It's not a blocker, but a nice to have since I'm already doing work with the agent config and we haven't updated protos recently.
~*DO NOT MERGE*:  changes in commit 25d3d29efc494e60c0a2fea483f877b49e3c9d27 (changes in micro-rdk) use dummy variables, this is just for verifying changes to compile properly. If we want the new protos but want to dive deep into getting the individual fields to be what they should right now, we can add tickets to put correct values.~
Values updated. 
- `local_name` refers to the name that a host sees a resource as (ex. the module's binary's name)
- `remote_path` refers to an array of remote machine …
> [RSDK-9979] update protos v0.1.394

- micro-rdk/src/common/app_client.rs
- micro-rdk/src/common/config.rs
- micro-rdk/src/common/conn/viam.rs
- micro-rdk/src/lib.rs
1 of 2 PRs to getting agent config from app (this PR) and storing them in NVS (next PR).
Still cleaning things up (getting rid of unwraps, etc), but wanted to get a first review going already in case there are major design changes requested.
> [RSDK-9887] get agent config from app

- templates/project/.github/workflows/publish.yml
- templates/project/Makefile
This will significantly reduce the friction for those developing firmware using the project template that want to make use of OTA by preparing a compiled binary as a release asset whenever a new version tag is pushed to the project. In theory, the download link to the release asset can be used in the configuration of the OTA service for a machine hosting the firmware.
However, this download link will only work when we have fixed the OTA service to properly handle redirects from the link location of the binary (likely to be addressed by [RSDK-10054](https://viam.atlassian.net/browse/RSDK-10054)).
[RSDK-10054]: https://viam.atlassian.net/browse/RSDK-10054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [RSDK-10067] - add release action workflow to project template

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- Makefile
- examples/modular-drivers/src/moisture_sensor.rs
- micro-rdk-ffi/Cargo.toml
- micro-rdk-ffi/build.rs
- micro-rdk-ffi/src/ffi/runtime.rs
- micro-rdk-nmea-macros/src/utils.rs
- micro-rdk-nmea/Cargo.toml
- micro-rdk-nmea/src/lib.rs
- micro-rdk-nmea/src/messages/pgns.rs
- micro-rdk-nmea/src/parse_helpers/enums.rs
- micro-rdk-nmea/src/parse_helpers/parsers.rs
- micro-rdk-nmea/src/viamboat/mod.rs
- micro-rdk-nmea/src/viamboat/sensors.rs
- micro-rdk-server/Cargo.toml
- micro-rdk/src/common/analog.rs
- micro-rdk/src/common/robot.rs
- micro-rdk/src/common/sensor.rs
- micro-rdk/src/esp32/coredump.rs
- micro-rdk/src/esp32/hcsr04.rs
- Added missing unit conversions (m/s to knots, meters to nautical miles)
- I've included a feature for inclusion in the micro-rdk-ffi for internal organization reasons
- Implements a variety of sensors using the NMEA parsing logic on raw data including
- Depth Sensor 
- Boat Movement Sensor
- Message Sensor (displaying data from specific PGNs)
- Debug Sensor (includes all raw and parsed data)
> [CONSULT-469] - add more PGN definitions and create sensors

- templates/project/Makefile
I have an older esp32-cam MCU board revision that only has 4mb of Flash and I had to reduce the baudrate from 460800 to 115200.  I was able to get the Rust based Viam Micro-RDK working on my ESP32-CAM and connected to the Viam Dashboard.
Along the journey, I improved the readability and customized the Makefile a bit.   I thought these enhancements might make the template easier to understand.
I removed the OTA partitions from my partitions.csv to fit in 4mb  but that's not worthy of a PR.
> ESP32 Makefile template enhancements

- .canon.yaml
- .github/workflows/esp32.yml
- .github/workflows/license_finder.yml
- .github/workflows/publish.yml
- templates/project/.canon.yaml
- templates/project/.github/workflows/publish.yml
This way, I can do another PR to update the docker image as I need and push it without it taking immediate effect, and then make another PR to upgrade to that new docker image along with any associated changes in the action definitions. Right now I can't do that.
Also valuable so we can re-run actions from old commits, and lookup what docker image was used to build a given commit, should we ever need to do that archaeology.
This does mean we will need to (remember to) not overwrite tags when pushing docker images, but at least now we can meaningfully do that. I intend to push the next docker images as `1.83.0-1-a{rm,md}64`
> RSDK-10268 Pin docker image in gh actions

- templates/project/build.rs
A small but important one. Without this, flashable (rather than OTA) firmware cannot be generated on GH for projects produced from the template - an important part of our cloud build plan.
> [RSDK-10120] Projects from templates can use provisioning

- micro-rdk-server/esp32/main.rs
- templates/project/src/main.rs
Also, cleanup logging terminology and harmonize between viam-micro-server and template projects.
> [RSDK-10281] Fix deprecation warnings in project template

- micro-rdk/src/esp32/certificate.rs
- micro-rdk/src/esp32/dtls.rs
- micro-rdk/src/esp32/tcp.rs
covers
RSDK-10196
RSDK-10197
RSDK-10198
RSDK-10200
RSDK-10201
> TLS & DTLS fixes

- micro-rdk/src/esp32/pwm.rs
@gvaradarajan will test on hardware when more of the platform modernization tickets are satisfied.
> [RSDK-10192] [RSDK-10199] Update PWM logic for ESP-IDF 5

- .canon.yaml
- .github/workflows/esp32.yml
- .github/workflows/format.yml
- .github/workflows/license_finder.yml
- .github/workflows/native.yml
- .github/workflows/publish.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- components_esp32.lock
- etc/docker/Dockerfile
- micro-rdk-server/Cargo.toml
- micro-rdk/src/common/conn/viam.rs
- micro-rdk/src/common/data_manager.rs
- micro-rdk/src/common/grpc_client.rs
- micro-rdk/src/common/ota.rs
- micro-rdk/src/common/robot.rs
- micro-rdk/src/common/webrtc/api.rs
- micro-rdk/src/common/webrtc/candidates.rs
- micro-rdk/src/common/webrtc/ice.rs
- micro-rdk/src/esp32/conn/network.rs
- micro-rdk/src/esp32/single_encoded_motor.rs
- micro-rdk/src/esp32/tcp.rs
- templates/module/Cargo.toml.liquid
- templates/project/.canon.yaml
- templates/project/.github/workflows/publish.yml
- templates/project/.gitignore
- templates/project/Cargo.toml.liquid
- `s/1.83/1.85g`
- Various clippy fixes that show up on new toolchain
- Explicitly select ESP-IDF v5.4.1 everywhere.
- Commit the `components_esp32.lock` file, which is now meaningful since we are using the mdns component
Once this is ready to go, I'll push the docker containers and restart the jobs so we can validate it works.
> [RSDK-10360] Upgrade to Rust 1.85

- micro-rdk-server/Cargo.toml
- micro-rdk/src/common/config_monitor.rs
- micro-rdk/src/common/conn/viam.rs
these are just small changes to 
~1. address an unused import warning~ 
2. rm ota from native compilation (only useful for specific testing)
3. silence an unused variable warning in native
> fix linting errors, rm ota from native

- micro-rdk-ffi/micrordklib-idf-component/CMakeLists.txt
We tried to do this here https://github.com/viamrobotics/micro-rdk/commit/0ccc9fc29133b1baa5b96651d98226f39240ee2d#diff-ed1421c19afa77da895d13381af64b9e0d604a7deda389355470f832609962d7L4 but we couldn't yet because `COMPONENT_VERSION` doesn't exist before ESP-IDF 5.
This just gets rid of one more touchpoint for updating versions during release.
I don't plan to merge this until we have a working ESP-IDF 5 compile so I can test it out, but I had it in my tree waiting, so it seemed worth getting it up for review.
> [RSDK-9841] Use COMPONENT_VERSION in FFI component with ESP-IDF 5

- .canon.yaml
- .github/workflows/esp32.yml
- .github/workflows/format.yml
- .github/workflows/license_finder.yml
- .github/workflows/native.yml
- .github/workflows/publish.yml
- .gitignore
- Cargo.lock
- Cargo.toml
- components_esp32.lock
- components_esp32c6.lock
- etc/docker/Dockerfile
- micro-rdk-server/Cargo.toml
- micro-rdk/src/common/conn/viam.rs
- micro-rdk/src/common/data_manager.rs
- micro-rdk/src/common/grpc_client.rs
- micro-rdk/src/common/ota.rs
- micro-rdk/src/common/robot.rs
- micro-rdk/src/common/webrtc/api.rs
- micro-rdk/src/common/webrtc/candidates.rs
- micro-rdk/src/common/webrtc/ice.rs
- micro-rdk/src/esp32/conn/network.rs
- micro-rdk/src/esp32/single_encoded_motor.rs
- micro-rdk/src/esp32/tcp.rs
- templates/module/Cargo.toml.liquid
- templates/project/.canon.yaml
- templates/project/.github/workflows/publish.yml
- templates/project/.gitignore
- templates/project/Cargo.toml.liquid
@npmenard - Only the second commit in this review is interesting, where we are patching in your `concurrent-queue`. The first is just a revert of the revert and associated conflict resolutions. I was able to flash this build and confirmed that it did not have immediate crashes like the prior rust 1.85 build did.
Note that it seems to me that applying the patch in the workspace `Cargo.toml` worked just fine. In fact, when I put it in the `Cargo.toml` for `micro-rdk-server` it told me it was being ignored. Happy to show you in person if you would like to see.
> [RSDK-10360] Rust 1.85 again

- Makefile
- templates/project/Makefile
Future versions of `cargo-espflash` (I'm running a build from HEAD that has fixes needed to flash an esp36c6) demand this flag, or error out with:
```
Partition table:   micro-rdk-server/esp32/partitions.csv
Error: espflash::partition_table::does_not_fit
× The partition table does not fit into the flash (4MB)
help: Make sure you set the correct flash size with the `--flash-size`
option
make: *** [build-esp32-ota] Error 1
```
Add this flag now so things don't break when we upgrade `cargo-espflash` to a version that introduces this requirement.
> use flash size argument for OTA targets

- micro-rdk-nmea/src/messages/message.rs
- micro-rdk-nmea/src/messages/pgns.rs
- micro-rdk-nmea/src/parse_helpers/enums.rs
- micro-rdk-nmea/src/parse_helpers/errors.rs
Manufacturers with specialized NMEA messages have to share a range of PGNs for defining their formats. As a result, there are different message formats with the same PGN that match on the value of a certain set of fields in the data past the appearance of the PGN. This PR treats all of the variants as a single PGN message enum with each variant being a struct that implements the Fieldset trait.
> [CONSULT-1023] support custom PGN formats used for proprietary messages

- micro-rdk-ffi/src/ffi/runtime.rs
- micro-rdk-server/esp32/main.rs
- micro-rdk/src/common/conn/viam.rs
- micro-rdk/src/common/grpc.rs
- micro-rdk/src/common/mod.rs
- micro-rdk/src/common/runtime.rs
- templates/project/src/main.rs
Also, log the restart reason on startup after we have initialized our logging buffers so it can be seen in the log viewer on app.viam.com
> [RSDK-9594] Don't produce a core on planned shutdowns

- micro-rdk-nmea-macros/src/attributes.rs
- micro-rdk-nmea-macros/src/composition.rs
- micro-rdk-nmea-macros/src/lib.rs
- micro-rdk-nmea-macros/src/utils.rs
- micro-rdk-nmea/src/parse_helpers/errors.rs
- micro-rdk-nmea/src/parse_helpers/parsers.rs
We were missing support for MMSI, String, and 32-bit float data types in the NMEA parsing macro. This fixes that.
> [CONSULT-1023] - implement rest of missed NMEA field types

- Cargo.lock
- micro-rdk-nmea/Cargo.toml
- micro-rdk-nmea/build.rs
- micro-rdk-nmea/src/gen/mod.rs
- micro-rdk-nmea/src/parse_helpers/parsers.rs
Adds auto-generation of [lookups with field type enumerations](https://canboat.github.io/canboat/canboat.html#lookupfieldtype-enumerations) from a JSON definitions file
> [CONSULT-1024] - generate NMEA fieldtype lookups from JSON definitions

- micro-rdk/src/common/config_monitor.rs
- micro-rdk/src/common/conn/viam.rs
Tested using a config that has a `modules` attribute, prevents reboot.
Example logging of the revision
```sh
I (45445) micro_rdk::common::config_monitor: mperez-
prev_revision: 1747332178801
next_revision: 1747332219939
```
> [RSDK-10692] use revision to check config change

- .gitignore
- micro-rdk/src/common/webrtc/ice.rs
There are lots of transient ICE log errors which give a false impression of instability. I frequently see "unable to properly process stun response IceStunEncodingError". Other changes in this PR are flybys.
> Update transient ICE log errors to warnings

- micro-rdk/src/esp32/i2c.rs
This a fix to reset the state of GPIO pin back to reset after waking up from sleep. Since the chip doesn't reset it's GPIO pin when waking up from sleep the pin may be configured in a way that make them unusable for I2C.
This shouldn't affect normal reset (power on, brown out etc..)
> Reset GPIO pin in when configuring I2C

- micro-rdk/src/common/data_collector.rs
- micro-rdk/src/common/motor.rs
tested using a fake motor with the `Position` data capture method on app.viam
To view a change in position on `FakeMotor`, set the power > 0.0 in the test/control section.
This PR does not include the `IsPowered` data capture method as we have not implemented the api yet. [ticket](https://viam.atlassian.net/browse/RSDK-10834?atlOrigin=eyJpIjoiMWVmYWVkMDRjMGMyNGExMzg1ZDEzOGZmMWEyN2JiYmQiLCJwIjoiaiJ9)
> [RSDK-8748] data capture motor position

- micro-rdk/src/common/board.rs
- micro-rdk/src/common/system.rs
- micro-rdk/src/esp32/board.rs
This changes uses the new system capabilities to initiate a deepsleep request.
This was initially started for testing the [support of other wakeup sources](https://viam.atlassian.net/browse/RSDK-10572?atlOrigin=eyJpIjoiZmFlYzJlM2MzNGIyNDQxMzliYTM1ZTQzMWFhYzI1ODAiLCJwIjoiaiJ9), however, the `set_power_mode` apis in both the Python SDK and Go SDK don't forward `extra` arguments ([ticket](https://viam.atlassian.net/browse/RSDK-10891?atlOrigin=eyJpIjoiN2VjYmZmMjg2N2U1NGVlY2E3MTE3OTM1NDYzZDM2NGEiLCJwIjoiaiJ9)). This would have been used for setting things such as `ulp_wakeup_enabled` or `interrupt_pin` for GPIO-based wakeups
This was tested using both the Python and Go SDK.
```sh
2025-06-04T22:40:17.896Z	DEBUG	client.networking.mdns.webrtc.client	utils@v0.1.143/logger.go:158	finished client …
```
> [RSDK-2437] use send_system_event for default impl Board set_power_mode
